Traceback (most recent call last):
  File "C:\Users\Jacky Ganun\env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Jacky Ganun\env\lib\site-packages\nbclient\client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Jacky Ganun\env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Jacky Ganun\env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Jacky Ganun\env\lib\site-packages\nbclient\client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Jacky Ganun\env\lib\site-packages\nbclient\client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Jacky Ganun\env\lib\site-packages\nbclient\client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from statsmodels.stats.weightstats import ttest_ind

t_value, p_value, df = ttest_ind(cond_1, cond_2)

print(f'Obtained t-value: {t_value}')
print(f'Obtained p-value: {p_value}')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [4][0m, in [0;36m<module>[1;34m[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstats[39;00m[38;5;21;01m.[39;00m[38;5;21;01mweightstats[39;00m [38;5;28;01mimport[39;00m ttest_ind
[0;32m      3[0m t_value, p_value, df [38;5;241m=[39m ttest_ind(cond_1, cond_2)
[0;32m      5[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mObtained t-value: [39m[38;5;132;01m{[39;00mt_value[38;5;132;01m}[39;00m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'statsmodels'
ModuleNotFoundError: No module named 'statsmodels'

